# version: "3.8"
services:
  db:
    image: postgres:15
    container_name: library-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-library}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: library-app
    depends_on:
      - db
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
  library-tests:
    build: .
    command: npm test
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

volumes:
  db_data:
